name: Build-Push-ECR

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
  
  Configure_Credentials:
    runs-on: ubuntu-20.04
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: eu-west-1

  Amazon_ECR_Login:
    runs-on: ubuntu-20.04
    steps:
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

  Build_Push_Images:
    runs-on: ubuntu-20.04
    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: bricksandmortar
        IMAGE_TAG: ${{ steps.extract_branch.outputs.branch }}
        RUN_NUMBER: ${{ github.run_number }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:react-$IMAGE_TAG-$RUN_NUMBER ./bricks-react
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:python-$IMAGE_TAG-$RUN_NUMBER ./python-env
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:react-$IMAGE_TAG-$RUN_NUMBER
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:python-$IMAGE_TAG-$RUN_NUMBER
